import { ContentType, WebcamProps } from "./definitions";

export const webcams: WebcamProps[] = [
  {
    nation: "ITA",
    region: "Valle d'Aosta",
    subRegion: "Valle del Gran San Bernardo",
    coordinates: { latitude: 45.839324, longitude: 7.153315 },
    resort: "Crevacol",
    label: "Arrivo seggiovia testa bassa",
    altitude: "2450 m",
    contentType: ContentType.IMG,
    source: "https://www.crevacol.it/meteo-e-webcam/",
    link: "https://pila.it/webcams/Crevacol01.jpg",
  },
  {
    nation: "ITA",
    region: "Valle d'Aosta",
    subRegion: "Valle del Gran San Bernardo",
    coordinates: { latitude: 45.828209, longitude: 7.159111 },
    resort: "Crevacol",
    label: "Saint Rhémy en Bosses",
    contentType: ContentType.IMG,
    source: "https://www.crevacol.it/meteo-e-webcam/",
    link: "https://www.lovevda.it/Media/LovevdaResp/Cache/Webcam/big_crevacol.jpg",
  },
  {
    nation: "ITA",
    region: "Valle d'Aosta",
    subRegion: "Valle del Gran San Bernardo",
    coordinates: { latitude: 45.819521, longitude: 7.194597 },
    resort: "Crevacol",
    label: "Foyer du fond, Flassin",
    altitude: "1380 m",
    contentType: ContentType.IMG,
    source: "https://www.crevacol.it/meteo-e-webcam/",
    link: "https://www.lovevda.it/Media/LovevdaResp/Cache/Webcam/big_soyen.jpg",
  },
  {
    nation: "ITA",
    region: "Valle d'Aosta",
    subRegion: "Valle d'Aosta",
    resort: "Pila",
    label: "Grimondet",
    altitude: "2348 m",
    contentType: ContentType.IFRAME,
    link: "https://webtv.feratel.com/webtv/?design=v3&cam=6316"
  },
  {
    nation: 'ITA',
    region: 'Piemonte',
    subRegion: 'Provincia di Cuneo',
    coordinates: { latitude: 44.23146, longitude: 7.78216 },
    resortGroup: 'Mondolè Ski',
    resort: 'Prato Nevoso',
    label: 'Chalet il Rosso',
    altitude: '2000 m',
    contentType: ContentType.IFRAME,
    link: 'https://pratonevoso.panomax.com/',
  },
];
